### PR TITLE
includes option not able to take more than 2 files?

### PR DESCRIPTION
**Pull request by bertpareyn**
I've been working on setting up a basic testing framework for our project. Yesterday I stumbled upon an issue where grunt will fail when including more than 2 files.

My configuration for grunt-ghost looks like this:

```
ghost: {
    dist: {
        filesSrc: ['node_modules/oae-core/*/tests/*.js', 'tests/casperjs/suites/'],
        options: {
            includes: [
                'tests/casperjs/util/include/content.js',
                'tests/casperjs/util/include/users.js',
                'tests/casperjs/util/include/util.js'
            ],
            failFast: false,
            printCommand: true
        }
    }
}
```

If I construct the same command manually and execute it as `casperjs test ...` it works just fine.

### CODE REVIEW

**Comment by bertpareyn** [comment]
I've narrowed it down to this line:

```
    if (options.printCommand) {
      wrap('\u001b[1m\u001b[4mCommand:\u001b[0m casperjs ' +
           command.join(' ') + ' \n');
    }
```

Setting `printCommand` to false fixes the problem for me.

Also, leaving `printCommand` to true but adding a space to a path seems to fix this as well.

```
'tests/casperjs/util/include/content.js' --> `'tests/casperjs/util/include/content util.js'
```

**Comment by bertpareyn** [comment]
Attached a fix.

**Comment by colinwren** [comment]
Im not quite clear on the problem. Is it that grunt fails when `printCommand` is true because of a bug that occurs when you use multiple files with `includes`?

**Comment by bertpareyn** [comment]
Correct.

**Comment by colinwren** [comment]
I ran it with your configuration and it had no errors, can you post the stack trace? If you run it with `--stack` it will have a meaningful error.

Thanks

**Comment by bertpareyn** [comment]
The only error I'm seeing is

```
Warning: Maximum call stack size exceeded Use --force to continue.

Aborted due to warnings.
```

**Comment by colinwren** [comment]
Sorry for taking so long on this, Thanks for your help!

I'll publish to npm now.

**Comment by bertpareyn** [comment]
Thanks! :ship:

**Pull request merged**
