### PR TITLE
Allow extra params to be passed through to Casper

### PR DESCRIPTION
**Pull request by m-allanson**
I made a quick addition to allow extra params to be passed through to Casper.  In my case I'm using it to pass through a port number, but you could use it for a bunch of stuff I guess.  There's some more details on the cli options here:  http://casperjs.org/cli.html  I hope it's helpful!

### CODE REVIEW

**Comment by colinwren** [comment]
Great, I wasn't aware of that feature.  I think that most people will use only named parameters because it's much clearer than getting a parameter by its position.  Because of this, ease of use of named parameters takes priority over ease of use of unnamed parameters. I like what you had in your first commit where for named parameters you could do:

``` javascript
args: {
  foo: 'bar'
}
```

This makes changing the name and/or value of the parameter much easier than changing them in:

``` javascript
'--foo=bar'
```

To support unnamed parameters, it could be something like this, where 'unnParam' is an unnamed parameter:

``` javascript
params: {
  foo: 'bar',
  unnParam: 'unNamed'
}
```

You could set the value of the unnamed param to a specific string ( I am open to strings other than  "unNamed" ) that identifies it as unnamed so when it is iterated over, only the key is pushed to the command.  Also the object should be called "params" instead of "args".

``` javascript
for (var p in params) {
  if (!params[p] === 'unNamed') {
    command.push('--' + p + '=' + params[p]);
  } else {
    command.push(p);
  }
}
```

If you make these changes I will happily accept your pull request, Thanks!

**Comment by m-allanson** [comment]
That all sounds very sensible, I've made the suggested changes.  Let me know if I've missed anything!

**Comment by colinwren** [comment]
The command array needs to have test in it to run [casper test](http://casperjs.org/testing.html#casper-test-command)

``` javascript
command = ['test']
```

The params var declaration should be inside the params if statement like this:

``` javascript
if (options.params) {
  var params = options.params;
}
```

because it is cleaner than declaring it at the top of the function.  Everything else is perfect.

**Comment by m-allanson** [comment]
Done and done.  I've had to change a couple of extra lines as it seems the casper test command doesn't work with unnamed params - see 90ddf04 for details.  I haven't looked in to why it doesn't work - it may a simple fix but for now I've just removed the offending code.

**Comment by colinwren** [comment]
Sounds good, thanks for your contribution!

**Pull request merged**
